trigger:
- 'importing-from-azure'

parameters:
- name: env
  displayName: 'Target env'
  default: dev
  values:
  - dev
  - test
  - prod
- name: LOAD_HOST
  displayName: Load testing host
  default: 'https://workplace.alpha.canada.ca'
  values:
  - 'https://workplace.alpha.canada.ca'
  - 'https://gcr2wp-dev.powerappsportals.com'
  - 'https://uat.workplace-milieudetravail.gc.ca/en-US'

stages:
- stage: LoadTest
  displayName: LoadTest
  jobs:
  - job: playwright
    pool:
      vmImage: 'ubuntu-latest'
      name: highcpu
    # container:
    #   image: mcr.microsoft.com/playwright:focal
    steps:
      - checkout: self

      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: 'sudo apt install -y node npm'      

      - task: Npm@1
        inputs:
          command: 'install'
        displayName: 'installing dependencies'

      - task: Npm@1
        inputs:
          command: 'custom'
          customCommand: 'run test-2x128 account-login/en'
        displayName: 'Running playwright tests'


