trigger:
- 'do-e2e-test'

stages:
- stage: E2ETest
  displayName: E2ETest
  jobs:
  - job: e2e_tests
    timeoutInMinutes: 120
    pool:
      vmImage: 'ubuntu-latest'
    container:
      image: mcr.microsoft.com/playwright:focal
      
    steps:
      - checkout: git@github.com:jaysonmc/temp-ocio-powerplatform-bdd-tests.git@refs/heads/e2e-pipeline
      - task: Npm@1
        inputs:
          command: 'install'
        displayName: 'installing dependencies'

# using CmdLine instead of Npm because npm buffers the entire output
      - task: CmdLine@2
        displayName: 'Running e2e tests'
        inputs:
          script: npm run test-regressions

