trigger:
- 'importing-from-azure'

stages:
- stage: LoadTest
  displayName: LoadTest
  jobs:
  - job: load_tests
    timeoutInMinutes: 10
    pool:
      vmImage: 'ubuntu-latest'
      name: highcpu
    # container:
    #   image: mcr.microsoft.com/playwright:focal
      
    steps:
      - checkout: self

      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            sudo apt install -y curl
            curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
            sudo apt install -y nodejs
            npx playwright install-deps 

      - task: Npm@1
        inputs:
          command: 'install'
        displayName: 'installing dependencies'

      - task: Npm@1
        inputs:
          command: 'custom'
          customCommand: 'run test-1x500 account-login/en'
        displayName: 'Running playwright tests'


