trigger:
- 'do-load-test'

stages:
- stage: LoadTest
  displayName: LoadTest
  jobs:
  - job: load_tests
    timeoutInMinutes: 120
    pool:
      vmImage: 'ubuntu-latest'
    container:
      image: mcr.microsoft.com/playwright:focal
      
    steps:
      - checkout: self
      - task: Npm@1
        inputs:
          command: 'install'
        displayName: 'installing dependencies'

# using CmdLine instead of Npm because npm buffers the entire output
      - task: CmdLine@2
        displayName: 'Running load tests'
        inputs:
          script: npm run test-regressions

