resources:
  repositories:
  - repository: e2etest # The name used to reference this repository in the checkout step
    type: github
    endpoint: jaysonmc
    name: jaysonmc/temp-ocio-powerplatform-bdd-tests
    ref: test-e2e

trigger:
- test-e2e

jobs:
  - job: e2etests
    timeoutInMinutes: 120
    pool:
        vmImage: 'ubuntu-latest'
    container:
        image: mcr.microsoft.com/playwright:focal
        volumes: [e2e-reviews]

    steps:
        - checkout: e2etest     
        - task: Npm@1
          inputs:
            command: 'install'
          displayName: 'installing dependencies'
# using CmdLine for the following instead of Npm because npm buffers the entire output
        - task: CmdLine@2  
          displayName: 'Running login e2e tests'
          continueOnError: true
          inputs:
            script: |
               HAIBUN_ENVC=${_ENVC} npm run test-pipeline-login

        - task: CmdLine@2 
          displayName: 'Running regression e2e tests'
          continueOnError: true        
          inputs:
            script: |
              HAIBUN_ENVC=${_ENVC} npm run test-pipeline-regressions

        - task: CmdLine@2
          displayName: 'Generate sarif indexes'
          continueOnError: true
          inputs:
            script: |
              HAIBUN_O_AZURESTORAGEBLOB_ACCOUNT=${_O_AZURESTORAGEBLOB_ACCOUNT} HAIBUN_O_AZURESTORAGEBLOB_KEY=${_O_AZURESTORAGEBLOB_KEY} HAIBUN_O_OUTREVIEWS_URI_ARGS=${_O_OUTREVIEWS_URI_ARGS} npm run test-pipeline-index-sarif

        - task: CmdLine@2
          displayName: 'Generate test result indexes'
          continueOnError: true
          inputs:
            script: |
              HAIBUN_O_AZURESTORAGEBLOB_ACCOUNT=${_O_AZURESTORAGEBLOB_ACCOUNT} HAIBUN_O_AZURESTORAGEBLOB_KEY=${_O_AZURESTORAGEBLOB_KEY} HAIBUN_O_OUTREVIEWS_URI_ARGS=${_O_OUTREVIEWS_URI_ARGS}  npm run test-pipeline-indexes

  # - job: publish_e2e_artifacts
  #   dependsOn: e2etests
  #   steps:
  #     - publish: '$(System.DefaultWorkingDirectory)'
  #       artifact: e2e_capture
  #       displayName: Publish e2e artifact            

  # - job: exit_if_failed
  #   dependsOn: publish_e2e_artifacts
  #   condition: eq(dependencies.e2etests.result,'Succeeded')
  #   steps:
  #     - script: echo e2e tests passed, continuing.
